### PR TITLE
Update passwords.js

### PR DESCRIPTION
**Pull request by duh-nm**
See Issue 296. Verified fix for items showing in trash on Nextcloud 11.

### CODE REVIEW

**Comment by duh-nm** [comment]
Sounds good, I hadn't tested with one that old. I can send another pull if that makes it easiest to add.

**Comment by fcturner** [comment]
Great 👍

**Comment by duh-nm** [comment]
Pop, spoke too soon I guess. That breaks nextcloud 11 again. Looks like I'll need to do anlittpe trial and error before the commit is let in

**Comment by pafcioooo** [comment]
As mentioned in #296 changing 'if (row.deleted || row.deleted == "true")' to 'if (row.deleted && row.deleted == "true")' helps. I am still using if (row.deleted == "true") which works for me on NC 11.0.1 and NC 11.0.2

**Comment by marius-wieschollek** [comment]
@pafcioooo I do not really understand what you want to archive with `if (row.deleted && row.deleted == "true")`.
AFAIK Javascript will behave similar to PHP an convert any value other than false/0/NULL to true since it is only a simple comparison. But the value is always a string, either `"true"` or `"false"` and will therefore always be converted to true. So `if (row.deleted && row.deleted == "true")` will result in true even if `row.deleted = "false"`.

I assume that this simple comparison is also the reason for #315 (which i experienced after pulling). I have now changed my local code to `if (row.deleted === true || row.deleted == "true")`. With this the row will only be considered as deleted if the value is exactly true or if it is the string value `"true"`. That way it should be compatible to OC 8.x.

I will try to file a pull request for this later today. The reason why i did not make a pull request for the first patch is that i think that the general error is that `row.deleted` contains a string instead of a boolean value and we re just covering this up currently.

**Comment by marius-wieschollek** [comment]
Ok, I made a pull request for the fix: #317

**Pull request merged**
