### PR TITLE
IzK666 - OC810

### PR DESCRIPTION
**Pull request by IzK666**
A small patch to work properly on new OC 8.1.0. Changes on this new version require to allow external links. Otherwise, favicons aren't loaded.

I have copied the code from here: "https://github.com/owncloud/news/blob/master/controller/pagecontroller.php". I have tested and works properly.

### CODE REVIEW

**Comment by fcturner** [comment]
Hey, thanks for that!

Any idea if this is backwards compatible with versions prior to 8.1.0? Else I need to include an if-this-then-that.

**Comment by IzK666** [comment]
It's impossible to downgrade!!!! :(

Don't matter. I have another way to install OC 8.0.4 (not from scratch). :)
I tell you something....

**Comment by fcturner** [comment]
That's nasty...

But my point is that it should work on all versions of ownCloud 8, for other users. People that download my app should be able to use it, no matter the version (8.0.* or 8.1.*) they use. 

So, will this patch work on 8.0.* too?

**Comment by IzK666** [comment]
Hi!
I have tested it under 8.0.4 and it doesn't work. Requires an if-then sentence, but I don't know how to get the OC version... :(

**Comment by fcturner** [comment]
Too bad they coded it this way... It probably means lots of apps won't support older versions of OC 8 whilst a lot of people keep using 

The answer to getting the OC version number is in core/settings/templates/personal.php or something like that. I will update the app today or tomorrow. Thanks for looking into this!

**Comment by fcturner** [comment]
Tackled with https://github.com/fcturner/passwords/commit/b4118c06ee8cfd7709205896913379db4fbba102, now implemented in the master branch. I will create a new release, so downloaders at apps.owncloud.org know this as well.

Thanks for the input :+1:

**Pull request closed without merging**
