### PR TITLE
8.0.6

### PR DESCRIPTION
**Pull request by IzK666**
Hi again!
I have made some changes...
It includes the previous address field, and some requested features: #18, #30, #31, #32, and #37.

### CODE REVIEW

**Comment by fcturner** [comment]
Hi! That's very nice of you, but I am/was *almost* done finishing all these issues myself... So we actually did the same work. I do like your style, you are a great coder. 

One thing, I just couldn't get saving settings to work with AJAX, so I am curious about your code. 

Our changes differ at another point too; some settings should be admin-only. Having this great, great pull request of you, I can finish the update this week. Would you like to test it out when it's done?

**Comment by fcturner** [comment]
Wow man, that's great work you did! Still shocked :smile:

**Comment by IzK666** [comment]
To save settings I just reuse your code and try to follow some how the "tutorial". I can't understand why is so bad the documentation! But I supose that this is the reason why not many apps (except for the official ones) don't have settings!

And yes. I can test your code ;)

**Comment by fcturner** [comment]
I hope to finish this tonight (UK time, it's now 5 pm here)

**Comment by fcturner** [comment]
Pulled in #40

**Pull request closed without merging**
