### PR TITLE
Correct header detection in file import

### PR DESCRIPTION
**Pull request by djibux**
Columns start from #CSVcolumn1 but detection starts from #CSVcolumn0

### CODE REVIEW

**Comment by fcturner** [comment]
Thanks! Will be in next release.

**Comment by fcturner** [comment]
Implemented as of [v16](https://github.com/fcturner/passwords/releases/tag/16).

**Comment by djibux** [comment]
The error is not corrected.  The code still reads `for (var i = 0; i < countColumns; i++) {`

**Comment by fcturner** [comment]
Huh? Didn't I commit this??? I don't get it!! I'll do this ASAP.

**Comment by fcturner** [comment]
L1815

**Comment by fcturner** [comment]
Original code was:
`for (var i = 0; i < countColumns; i++) {`

@IzK666 edited it to:
`for (var i = 0; i <= countColumns; i++) {`

And your solution is:
`for (var i = 1; i <= countColumns; i++) {`

So... Who is right??

**Comment by djibux** [comment]
I am :)

**Comment by fcturner** [comment]
Implemented: https://github.com/fcturner/passwords/commit/f65692b4af238f85d570945edc565c729bb5159d

**Pull request closed without merging**
