### PR TITLE
Translate 15

### PR DESCRIPTION
**Pull request by IzK666**
Spanish and catalan translated for version 15.
English mistake solved.

### CODE REVIEW

**Comment by fcturner** [comment]
Thanks!

Wow, such an idiot mistake, albeit a native English tongue :cry:

**Comment by fcturner** [comment]
Will be in v16. Would you like pulling requests from my master, not a specific version number? Thanks!

**Comment by fcturner** [comment]
Will be v17. Forgot it, honestly :cry:

**Comment by IzK666** [comment]
I'll update the translation files again (tomorrow). I'll fix the error again. :)

**Pull request closed without merging**
