### PR TITLE
Settings upgrade

### PR DESCRIPTION
**Pull request by IzK666**
I hope you like this little change.
The settings sections (administration and personal) has no "Save" button at all.
Having only "passwords" section with this button is a bit awkward and is very easy to forget pressing the button before leaving the site.

IzK

### CODE REVIEW

**Comment by fcturner** [comment]
Thanks! Definitely good idea.

I wouldn't want to lose the `<span class="msg-passwords"></span>` though, since I want feedback on an actual save. And the CSS should be altered too. But besides that, great add.

**Comment by fcturner** [comment]
I will merge this when I am done implementing a trash bin, shouldn't take too long.

**Comment by fcturner** [comment]
Will be moved to next version :smiley: 
But hey, it never takes long :)

**Comment by fcturner** [comment]
Really nice, but I would like you to test the code first and then create a pull request. 

If you had tested this, you would have noticed that for example:
```js
$('hide_usernames').change(function () {
	settings.setUserKey('hide_usernames', $(this).is(":checked"));
});
```
won't work, because the jQuery-selector `$('hide_usernames')` is an ID, and thus needs `#` as prefix:
```js
$('#hide_usernames').change(function () {
	settings.setUserKey('hide_usernames', $(this).is(":checked"));
});
```

But I do appreciate you putting your time in my app. That's great!

**Comment by fcturner** [comment]
I am almost done, and fixed this already by the way :smile:

**Comment by IzK666** [comment]
I'm sorry for the mistake. Although useless now, I have updated the pull request.

**Comment by fcturner** [comment]
I will release 8.0.13 now, including this feature.

**Pull request closed without merging**
