### PR TITLE
Missing escape password if value is modified.

### PR DESCRIPTION
**Pull request by IzK666**
Escaping the password value when modified.

### CODE REVIEW

**Comment by fcturner** [comment]
Nice one! Thanks!

**Comment by fcturner** [comment]
Huh? This doesn't do anything. The line you edited is only for 'the show'. The update is already done to the database and this line is ignored when the page gets reloaded. I don't see why this edit needs to be done...

**Comment by IzK666** [comment]
My fix is for that (an example):
You have a site with password: "abc". When you modify this password to "abc<def>end", the site isn't reloaded (only modified with js), and the password don't show correctly: "abcend" without my fix.

You have already resolved every issue related to the database.

**Comment by fcturner** [comment]
"abcend" and "abcend" are the same. What do you mean? 
Can you describe the steps more clearly please?

**Comment by IzK666** [comment]
Comment updated. The comments require to escape the special characters \< and \> too :laughing:

**Comment by fcturner** [comment]
Right, now I see. 
Thanks!

**Comment by fcturner** [comment]
Implemented in master: https://github.com/fcturner/passwords/commit/be827a09d9c74f5faaf6182011c9a7041e788e5b

Thanks!

**Pull request closed without merging**
