### PR TITLE
Visual enhancements

### PR DESCRIPTION
**Pull request by IzK666**
Small enhancements specially for mobile phone:
script.js: Don't "prompt" value in title: it makes imposible to copy the value to clipboard. I added a title.
style.css: For small screens, edit and copy should be in different lines.

Suggestion: The category field can be shown in smaller screens like 1050px.

### CODE REVIEW

**Comment by fcturner** [comment]
Yes, I saw this yesterday. Should've been `prompt('', [value])`. This one is better, thanks!

**Comment by fcturner** [comment]
I'm adding one extra line for translation:
`Would you like to backup deleted passwords too?`

Something like 
`¿Le eliminado contraseñas incluso en la copia de seguridad?` 
for Spanish?

**Comment by IzK666** [comment]
Better: "¿Quieres incluir además las contraseñas de la papelera?"
It's not an exact translation word by word, but I think it's fully understandable. I supose that this question is made after the user clicks on the backup button.

PS: Why spanish hasn't a simple word for 'backup'? :cry:

**Comment by fcturner** [comment]
How strange? And they don't use the word Backup in English? That's what German and Dutch people do.
How do you say it in Catalan?

**Pull request merged**
