### PR TITLE
Small editor

### PR DESCRIPTION
**Pull request by IzK666**
Hi!

I have created a new way to edit values, instead of using a prompt.
It allows to create long notes and use the password generator.

Hope you like the addon.
As always, I attach some screenshots. :wink:

IzK
screenshot1
screenshot2
screenshot3

### CODE REVIEW

**Comment by fcturner** [comment]
WOW! Man, I do like your style!!

I can use this a beginning to JS-security for hidden values as well (instead of CSS). Great. I will look into this quickly and implement it.

**Comment by fcturner** [comment]
I am thrilled by your additions! It's really great!

But as I cannot change this code before implementing it, I'll just comment on some things:
* An overlay field is already available on every ownCloud page. It has the right CSS-location, Z-index, and so on. Almost at the end of the body you can find (you need to remove the `display: none`, by editing the style attribute and change opacity):
```html
<div id="cboxOverlay" style="display: none;"></div>
```
* The height of the Notes field should be defined, to prevent browsers have their own interpretation. A height of twice a normal field (26 x 2 = 52px) should be fine. Your screenshot suggest three rows, but on some laptops (screen height of appr. 800 px, functional browser part at fullscreen appr. 650px) the navigation pane might get too 'filled'.
* When calling the popup for Notes, the title should be translated too. The reason why `thead` doesn't need to be translated, is because it is translated already :smile: PHP took care of that when the page was loaded. Since column 13 doesn't have a `thead` title, this must be defined, as you did. So just change:
```js
210    popUp("Notes", old_value, col);
```
to
```js
210   popUp(t('passwords', 'Notes'), old_value, col);
```
* Fields like `#gen_lower2`, `#gen_upper2` are hard to identity when changing code later. Instead, you might want to id those fields as `#(name)_popup`, such as `#gen_lower_popup`. But, an even more delicate solution is to append this part from the navigation pane to the popup! Then all JS-codes IF's and THEN's are reusable.

Are you able to edit these things? Then I will implement it immediately.

**Comment by IzK666** [comment]
Hi!
Thanks for your comments :)

I can't find any 'cboxOverlay' :disappointed: I have search on the entire code of owncloud and there is almost no trace. (only inside apps/firstrunwizard/css/colorbox.css).
I'm using OC 8.1.0.

In the popup, the height of Notes are 5 rows and are displayed correctly under FF, Vivaldi and Opera 12.
In the navigation part, I think it could be fine with 3 rows, as in the next picture. Look at this screenshot of my old netbook (1024x600):
screenshot-netbook
It requires to scroll, but it was already required when generating a new password. I forgot to mention that I have rearranged the items only on my computer and not on the commit.

I'll upload the commit again.

**Comment by fcturner** [comment]
I guess the `cboxOverlay` is only present when firstrunwizard is activated. Might indeed be old inheritance from previous versions.

Screenshot from Files app:
image

**Comment by IzK666** [comment]
You're right.
Only when "First Run Wizard" is enabled, this div exists. 

The commit is ready. I have changed variable names, set a height of 52 for notes on textarea and repair the mistake.
The final part about reusing the code, I don't understand what you mean.

**Comment by fcturner** [comment]
Great. Never mind the last part. You edits are superb.

**Comment by fcturner** [comment]
As you can see in the latest release I did some very small polishing (the labels in your password generator didn't match their input field, I chose to do some CSS edits and some other things). I am glad with this release, so thanks again!

**Comment by IzK666** [comment]
One extra detail: yesterday, almost at the same time you released the new version, a new OC version was released (8.1.1).
I have already tested and works perfect!

**Comment by fcturner** [comment]
Great! I am now on 8.1.1 too. Seems to be working perfectly :smile:

**Pull request merged**
